services:
  - type: web
    name: spicyhunt-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.10.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
