import { Inter } from "next/font/google";
import "./styles/globals.css";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";
import { LoadingProvider } from "./context/LoadingContext";
import { LanguageProvider } from "./context/LanguageContext";
import { PageProfileFetcher } from "./components/PageProfileFetcher/PageProfileFetcher";
import { ProfileFetchStatus } from "./components/ProfileFetchStatus/ProfileFetchStatus";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spicyhunt",
  description: "Generated by create next app",
  
};

// Tách phần client component ra một component riêng
function ClientLayout({ children }) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LanguageProvider>
        <AuthProvider>
          <CartProvider>
            <PageProfileFetcher />
            <ProfileFetchStatus />
            <Toaster position="top-center" />
            {children}
          </CartProvider>
        </AuthProvider>
      </LanguageProvider>
    </Suspense>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
